export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const Layout = ({children}) => (
    <>
        {children}
    </>
);

export default Layout;
